//USER TYPES
export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_SIGNIN = 'USER_SIGNIN'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR'
export const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR'
export const USER_LOADING = 'USER_LOADING'
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR'
export const USER_RESET = 'USER_RESET'
export const USER_REMOVE = 'USER_REMOVE'
export const GET_USERS = 'GET_USERS'
export const GET_ME = 'GET_ME'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'

//POST TYPES
export const DATA_ADD = 'DATA_ADD'
export const DATA_UPDATE = 'DATA_UPDATE'
export const DATA_DELETE = 'DATA_DELETE'
export const DATA_ERROR = 'DATA_ERROR'
export const DATA_GET = 'DATA_GET'
export const DATA_LOADING = 'DATA_LOADING'
export const GET_STORAGE = 'GET_STORAGE'

